# Generated by Django 3.2.7 on 2021-09-08 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=140)),
                ('tweeted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tweeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweeter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
