# Generated by Django 3.2.7 on 2021-09-09 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
