# Generated by Django 3.2.7 on 2021-09-10 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0003_tweet_follow_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='follow_check',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
