# Generated by Django 3.2.7 on 2021-09-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_alter_tweet_follow_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='follow_check',
        ),
    ]
