# Generated by Django 3.2.7 on 2021-09-10 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0006_remove_tweet_follow_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='follow_check',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
