# Generated by Django 3.2.7 on 2021-09-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_tweet_follow_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='follow_check',
        ),
    ]
