# Generated by Django 3.2.7 on 2021-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '0002_tweet_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='tweet.Tweet')),
            ],
        ),
    ]
