# Generated by Django 3.2.7 on 2021-09-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_alter_tweet_follow_check'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tweet.Tweet'),
        ),
    ]
