# Generated by Django 3.2.7 on 2021-09-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0003_remove_myuser_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='follower',
            field=models.BooleanField(default=False),
        ),
    ]
