# Generated by Django 3.2.7 on 2021-09-09 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0004_myuser_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='friend',
        ),
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='follower',
        ),
        migrations.AddField(
            model_name='myuser',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
