# Generated by Django 3.2.7 on 2021-09-09 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0005_auto_20210909_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='follower',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
