# Generated by Django 3.2.7 on 2021-09-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0006_auto_20210909_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='display_name',
        ),
    ]
